format = """
$directory\
[](fg:blue0 bg:orange)\
$git_branch\
$git_commit\
$git_status\
[](fg:orange) \
"""

add_newline = false

palette = 'tokyonight'
[palettes.tokyonight]
bg_dark = "#1f2335"
blue0 = "#3d59a1"
fg = "#c0caf5"
fg_gutter = "#3b4261"
orange = "#ff9e64"

[directory]
style = "bg:blue0 fg:fg"
read_only_style = "bg:blue0 fg:fg"
format = """
[](fg:bg_dark bg:blue0)[ $path ]($style)\
[$read_only]($read_only_style)\
"""

[git_branch]
always_show_remote = true
format = "[ $symbol$branch(:$remote_branch) ]($style)"
style = "bg:orange fg:fg_gutter"

[git_commit]
style = "bg:orange fg:fg_gutter"
format = "[ \\($hash$tag\\) ]($style)"

[git_status]
style = "bg:orange fg:fg_gutter"
ahead = " ↑"
behind = " ↓"
deleted = ""
untracked = "?"
modified = ""
staged = ""
stashed = ""
format = '([\[$all_status$ahead_behind\]]($style))'
