add_newline = false

format = """
$directory\
[](fg:#61AFEF bg:#C8A2C8)\
$git_branch\
$git_commit\
$git_status\
[](fg:#C8A2C8) \
"""

[directory]
style = "bg:#61AFEF fg:#f5f5dc"
read_only_style = "bg:#61AFEF fg:#f5f5dc"
format = """
[](fg:#1f2335 bg:#61AFEF)[ $path ]($style)\
[$read_only]($read_only_style)\
"""

[git_branch]
always_show_remote = true
format = "[ $symbol$branch(:$remote_branch) ]($style)"
style = "bg:#C8A2C8 fg:#193549"

[git_commit]
style = "bg:#C8A2C8 fg:#193549"
format = "[ \\($hash$tag\\) ]($style)"

[git_status]
style = "bg:#C8A2C8 fg:#193549"
ahead = "↑"
behind = "↓"
deleted = "ⅹ"
untracked = "?"
modified = "!"
staged = ""
format = '([\[$all_status$ahead_behind\]]($style))'
